[build]
base = "ait-app"
command = "npm ci --no-audit --no-fund && CI= npm run build:web"
publish = "build"

[build.environment]
NODE_VERSION = "18.20.3"
NODE_OPTIONS = "--max_old_space_size=3072"
NPM_FLAGS = "--omit=dev"

[[headers]]
  for = "/pwabuilder-sw.js"
  [headers.values]
  Cache-Control = "no-cache"
  Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
  Cache-Control = "no-cache"

[[headers]]
  for = "/icons/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"